/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/items': RouteRecordInfo<'/items', '/items', Record<never, never>, Record<never, never>, '/items/[itemId]'>,
    '/items/[itemId]': RouteRecordInfo<'/items/[itemId]', '/items/:itemId', { itemId: ParamValue<true> }, { itemId: ParamValue<false> }>,
    '/operators': RouteRecordInfo<'/operators', '/operators', Record<never, never>, Record<never, never>, '/operators/[operatorId]'>,
    '/operators/[operatorId]': RouteRecordInfo<'/operators/[operatorId]', '/operators/:operatorId', { operatorId: ParamValue<true> }, { operatorId: ParamValue<false> }>,
    '/plan': RouteRecordInfo<'/plan', '/plan', Record<never, never>, Record<never, never>, '/plan/' | '/plan/[operatorId]'>,
    '/plan/': RouteRecordInfo<'/plan/', '/plan', Record<never, never>, Record<never, never>>,
    '/plan/[operatorId]': RouteRecordInfo<'/plan/[operatorId]', '/plan/:operatorId', { operatorId: ParamValue<true> }, { operatorId: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/items.vue': {
      routes: '/items' | '/items/[itemId]'
      views: 'default'
    }
    'src/pages/items/[itemId].vue': {
      routes: '/items/[itemId]'
      views: never
    }
    'src/pages/operators.vue': {
      routes: '/operators' | '/operators/[operatorId]'
      views: 'default'
    }
    'src/pages/operators/[operatorId].vue': {
      routes: '/operators/[operatorId]'
      views: never
    }
    'src/pages/plan.vue': {
      routes: '/plan' | '/plan/' | '/plan/[operatorId]'
      views: 'default'
    }
    'src/pages/plan/index.vue': {
      routes: '/plan/'
      views: never
    }
    'src/pages/plan/[operatorId].vue': {
      routes: '/plan/[operatorId]'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
